#define _POSIX_C_SOURCE 200809L
#include "cbs.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

static char *read_all(const char *path,size_t *length){FILE *f=fopen(path,"rb");long n;char *p;if(!f||fseek(f,0,SEEK_END)||(n=ftell(f))<0||fseek(f,0,SEEK_SET))return NULL;p=cbs_allocate((size_t)n+1);if(fread(p,1,(size_t)n,f)!=(size_t)n){fclose(f);free(p);return NULL;}fclose(f);p[n]='\0';*length=(size_t)n;return p;}
static int write_value(const char *path,const char *value){FILE *f=fopen(path,"wb");size_t n=strlen(value);return f&&fwrite(value,1,n,f)==n&&fclose(f)==0;}

int main(int argc,char **argv){char template[]="/tmp/cbs-source-test-XXXXXX",good[512],empty[512],bad[512];char *base,*text,*resolved;size_t length;CbsTokenList tokens;CbsNode *doc;CbsSourceSet set;CbsExecutionContext context;FILE *capture;int saved;char diagnostic[2048];size_t n;int ok=1;memset(&tokens,0,sizeof(tokens));memset(&set,0,sizeof(set));memset(&context,0,sizeof(context));if(argc!=2)return 2;base=mkdtemp(template);if(!base)return 1;snprintf(good,sizeof(good),"%s/good",base);snprintf(empty,sizeof(empty),"%s/empty",base);snprintf(bad,sizeof(bad),"%s/bad",base);if(!write_value(good,"abc")||!write_value(empty,"")||!write_value(bad,"wrong"))return 1;text=read_all(argv[1],&length);if(!text||!cbs_lex(argv[1],text,length,&tokens))return 1;doc=cbs_parse(argv[1],text,length,&tokens);if(!doc||!cbs_validate(doc,argv[1],text)||!cbs_sources_from_document(doc,&set))ok=0;if(ok&&(set.count!=2||set.items[0].url_count!=2||strcmp(set.items[0].urls[1],"https://mirror.invalid/upstream")||cbs_sources_apply_execution_context(&set,&context)))ok=0;if(ok&&!cbs_source_verify(&set.items[0],good,argv[1],text,set.items[0].urls?doc->location:doc->location))ok=0;if(ok&&cbs_sources_apply_execution_context(&set,&context))ok=0;capture=tmpfile();saved=dup(STDERR_FILENO);if(ok&&capture&&saved>=0&&dup2(fileno(capture),STDERR_FILENO)>=0){if(cbs_source_verify(&set.items[1],bad,argv[1],text,doc->location))ok=0;fflush(stderr);dup2(saved,STDERR_FILENO);close(saved);rewind(capture);n=fread(diagnostic,1,sizeof(diagnostic)-1,capture);diagnostic[n]='\0';fclose(capture);if(!strstr(diagnostic,"CPDL-E5001")||!strstr(diagnostic,"source `empty`")||!strstr(diagnostic,"expected e3b0")||!strstr(diagnostic,"computed 8810"))ok=0;}else ok=0;if(ok&&(!cbs_source_verify(&set.items[1],empty,argv[1],text,doc->location)||!cbs_sources_apply_execution_context(&set,&context)))ok=0;if(ok){resolved=cbs_resolve_value("${source.upstream}|${source.empty}",CBS_TOKEN_STRING,&context);if(!strstr(resolved,good)||!strstr(resolved,empty))ok=0;free(resolved);}cbs_source_set_destroy(&set);cbs_node_destroy(doc);cbs_token_list_destroy(&tokens);free(text);if(!ok){fputs("named source tests: FAIL\n",stderr);return 1;}puts("named source tests: PASS (mirrors, verification, gated bindings)");return 0;}
