#include "cbs.h"
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
static int collect(const char *root,const char *relative,CbsManifestEntry **items,size_t *count,size_t *capacity){char path[4096];DIR*d;struct dirent*e;if(snprintf(path,sizeof(path),"%s/%s",root,relative)>= (int)sizeof(path))return 0;d=opendir(path);if(!d)return 0;while((e=readdir(d))!=NULL){char child[4096];struct stat st;if(strcmp(e->d_name,".")==0||strcmp(e->d_name,"..")==0)continue;if(snprintf(child,sizeof(child),"%s%s%s",relative,relative[0]?"/":"",e->d_name)>=(int)sizeof(child)){closedir(d);return 0;}if(snprintf(path,sizeof(path),"%s/%s",root,child)>=(int)sizeof(path)||lstat(path,&st)!=0){closedir(d);return 0;}if(S_ISDIR(st.st_mode)){if(!collect(root,child,items,count,capacity)){closedir(d);return 0;}}else if(S_ISREG(st.st_mode)){if(*count==*capacity){size_t next=*capacity?*capacity*2:16;CbsManifestEntry*n=realloc(*items,next*sizeof(*n));if(!n){closedir(d);return 0;}*items=n;*capacity=next;}(*items)[*count].path=cbs_duplicate(child);(*items)[*count].type='f';(*items)[*count].mode=(unsigned)(st.st_mode&07777);(*items)[*count].size=(unsigned long long)st.st_size;(*items)[*count].digest=cbs_duplicate_range("",0);{char digest[65];if(!cbs_digest_file(path,digest)){closedir(d);return 0;}free((char *)(*items)[*count].digest);(*items)[*count].digest=cbs_duplicate(digest);}(*count)++;}}closedir(d);return 1;}
int cbs_manifest_write(const char *root,const char *output){CbsManifestEntry*items=NULL;size_t count=0,capacity=0,i;FILE*f;if(!collect(root,"",&items,&count,&capacity)){free(items);return 0;}qsort(items,count,sizeof(*items),cbs_manifest_compare);f=fopen(output,"wb");if(!f){free(items);return 0;}for(i=0;i<count;++i){if(fprintf(f,"%c %o %llu %s %s\n",items[i].type,items[i].mode,items[i].size,items[i].digest,items[i].path)<0){fclose(f);return 0;}free((char*)items[i].path);free((char*)items[i].digest);}free(items);return fclose(f)==0;}
int cbs_manifest_compare(const void *left, const void *right){const CbsManifestEntry *a=left,*b=right;return strcmp(a->path,b->path);}
