#include "cbs.h"
#include <stdio.h>
#include <stdlib.h>
#include <zstd.h>
#include <sys/stat.h>
#include <unistd.h>
#include <stdint.h>
#include <string.h>
int cbs_cixpkg_compress(const char *input,const char *output){FILE *in=fopen(input,"rb"),*out;long n;void *src,*dst;size_t bound,written;if(!in||fseek(in,0,SEEK_END)|| (n=ftell(in))<0||fseek(in,0,SEEK_SET)){if(in)fclose(in);return 0;}src=malloc((size_t)n);if(!src||fread(src,1,(size_t)n,in)!=(size_t)n){free(src);fclose(in);return 0;}fclose(in);bound=ZSTD_compressBound((size_t)n);dst=malloc(bound);if(!dst){free(src);return 0;}written=ZSTD_compress(dst,bound,src,(size_t)n,19);free(src);if(ZSTD_isError(written)){free(dst);return 0;}out=fopen(output,"wb");if(!out||fwrite(dst,1,written,out)!=written||fclose(out)!=0){if(out)fclose(out);free(dst);return 0;}free(dst);return 1;}

int cbs_cixpkg_decompress(const char *input,const char *output){FILE*in=fopen(input,"rb"),*out;long n;void*src,*dst;unsigned long long size;size_t written;if(!in||fseek(in,0,SEEK_END)||(n=ftell(in))<0||fseek(in,0,SEEK_SET)){if(in)fclose(in);return 0;}src=malloc((size_t)n);if(!src||fread(src,1,(size_t)n,in)!=(size_t)n){free(src);if(in)fclose(in);return 0;}fclose(in);size=ZSTD_getFrameContentSize(src,(size_t)n);if(size==ZSTD_CONTENTSIZE_ERROR||size==ZSTD_CONTENTSIZE_UNKNOWN||size>1024ULL*1024ULL*1024ULL){free(src);return 0;}dst=malloc((size_t)size+1);if(!dst){free(src);return 0;}written=ZSTD_decompress(dst,(size_t)size,src,(size_t)n);free(src);if(ZSTD_isError(written)||written!=(size_t)size){free(dst);return 0;}out=fopen(output,"wb");if(!out||fwrite(dst,1,written,out)!=written||fclose(out)!=0){if(out)fclose(out);free(dst);return 0;}free(dst);return 1;}

int cbs_install_atomic(const char *staged,const char *destination,unsigned mode){if(staged==NULL||destination==NULL||chmod(staged,mode)!=0)return 0;return rename(staged,destination)==0;}
int cbs_compare_files(const char *left,const char *right){FILE*a=fopen(left,"rb"),*b=fopen(right,"rb");int x,y;if(!a||!b){if(a)fclose(a);if(b)fclose(b);return 0;}do{x=fgetc(a);y=fgetc(b);if(x!=y){fclose(a);fclose(b);return 0;}}while(x!=EOF);fclose(a);fclose(b);return 1;}

static int package_blob(const char *path, unsigned char **data, size_t *size){FILE*f=fopen(path,"rb");long n;if(!f||fseek(f,0,SEEK_END)||(n=ftell(f))<0||fseek(f,0,SEEK_SET)){if(f)fclose(f);return 0;}*data=malloc((size_t)n);if(*data==NULL||fread(*data,1,(size_t)n,f)!=(size_t)n){free(*data);fclose(f);return 0;}fclose(f);*size=(size_t)n;return 1;}
static void put64(unsigned char *p,uint64_t v){size_t i;for(i=0;i<8;++i)p[i]=(unsigned char)(v>>(i*8));}
static uint64_t get64(const unsigned char *p){uint64_t v=0;size_t i;for(i=0;i<8;++i)v|=(uint64_t)p[i]<<(i*8);return v;}
int cbs_cixpkg_write(const char *payload,const char *package_path,const char *identity){unsigned char*src,*dst,digest[65],header[8+8+8+64+128];size_t size,bound,written,idlen;FILE*f;if(!identity||!cbs_digest_file(payload,(char*)digest))return 0;if(!package_blob(payload,&src,&size))return 0;bound=ZSTD_compressBound(size);dst=malloc(bound);if(!dst){free(src);return 0;}written=ZSTD_compress(dst,bound,src,size,19);free(src);if(ZSTD_isError(written)){free(dst);return 0;}memcpy(header,"CIXPKG\0\1",8);put64(header+8,(uint64_t)(8+8+8+64+128));put64(header+16,(uint64_t)size);memcpy(header+24,digest,64);idlen=strlen(identity);if(idlen>=128)idlen=127;memset(header+88,0,128);memcpy(header+88,identity,idlen);f=fopen(package_path,"wb");if(!f||fwrite(header,1,sizeof(header),f)!=sizeof(header)||fwrite(dst,1,written,f)!=written||fclose(f)!=0){if(f)fclose(f);free(dst);return 0;}free(dst);return 1;}
int cbs_cixpkg_verify(const char *package_path,char *identity,size_t identity_size){unsigned char h[216],*compressed,*raw;size_t size,written;uint64_t raw_size;FILE*f=fopen(package_path,"rb");if(!f||fread(h,1,sizeof(h),f)!=sizeof(h)||memcmp(h,"CIXPKG\0\1",8)!=0){if(f)fclose(f);return 0;}raw_size=get64(h+16);fseek(f,0,SEEK_END);{long n=ftell(f);if(n<216||fseek(f,216,SEEK_SET)!=0){fclose(f);return 0;}size=(size_t)n-216;}compressed=malloc(size);raw=malloc((size_t)raw_size);if(!compressed||!raw||fread(compressed,1,size,f)!=size){free(compressed);free(raw);fclose(f);return 0;}fclose(f);written=ZSTD_decompress(raw,(size_t)raw_size,compressed,size);free(compressed);if(ZSTD_isError(written)||written!=(size_t)raw_size){free(raw);return 0;}if(identity!=NULL&&identity_size>0){strncpy(identity,(char*)(h+88),identity_size-1);identity[identity_size-1]='\0';}free(raw);return 1;}
